# Generated by Django 3.1.5 on 2021-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210129_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='urlName',
            field=models.CharField(default='no', max_length=30),
            preserve_default=False,
        ),
    ]
