# Generated by Django 3.1.5 on 2021-01-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tool_urlname'),
    ]

    operations = [
        migrations.CreateModel(
            name='variations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=400, verbose_name='description')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tool')),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=120)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tool')),
            ],
        ),
    ]
