# Generated by Django 3.1.5 on 2021-02-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210215_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='resoucres',
            new_name='resources',
        ),
    ]
