# Generated by Django 3.1.5 on 2021-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210215_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='isReady',
            field=models.BooleanField(default=True),
        ),
    ]
