# Generated by Django 3.1.5 on 2021-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tool_isready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
    ]
