# Generated by Django 3.1.5 on 2021-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210217_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, to='main.resources'),
        ),
    ]
