# Generated by Django 3.1.5 on 2021-02-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210217_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='main.variations'),
        ),
    ]
