# Generated by Django 3.1.7 on 2021-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210217_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='color',
            field=models.CharField(default='#ede7e6', max_length=7),
        ),
    ]
