# Generated by Django 3.1.7 on 2021-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tool_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='grad2',
            field=models.CharField(default='rgb(4, 8, 0)', max_length=24),
        ),
        migrations.AddField(
            model_name='tool',
            name='gradColor',
            field=models.CharField(default='rgb(196, 20, 98)', max_length=24),
        ),
    ]
