# Generated by Django 3.1.7 on 2021-03-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210322_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='gradColor',
            new_name='grad1',
        ),
        migrations.AddField(
            model_name='tool',
            name='cat',
            field=models.CharField(default='Traditional', max_length=12),
        ),
    ]
